spring:
  application:
    name: tisaicore

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/tisaicore-db}
    username: ${SPRING_DATASOURCE_USERNAME:tisailag}
    password: ${SPRING_DATASOURCE_PASSWORD:L4(5dB4,rKH@!OQN}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false

server:
  port: 8080

rsa:
  public-key: classpath:keys/public.pem
  private-key: classpath:keys/private.pem

storage:
  gcp:
    bucket-name: ${GCP_BUCKET_NAME:tisaicore-bucket}
  local:
    upload-dir: ${LOCAL_UPLOAD_DIR:./uploads}
    base-url: ${LOCAL_BASE_URL:http://localhost:8080}
